// On a fresh homepage: browse eval tests/cities-scroll.browser.js
// Runs as an async function body in the browser's evaluation tool.
return (async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  await document.fonts.ready;
  await wait(1000);
  const stage = document.querySelector('[data-home-view]');
  const intro = document.querySelector('[data-scroll-view="intro"]');
  const cities = document.querySelector('[data-scroll-view="cities"]');
  const enter = document.querySelector('button[aria-label="Enter Cities"]');
  const back = document.querySelector('button[aria-label="Back to home"]');
  const assert = (condition, message) => { if (!condition) throw new Error(message); };
  assert(stage && intro && cities && enter && back, 'Both views and arrows must exist');
  const wheel = (deltaY, target = intro) => target.dispatchEvent(new WheelEvent('wheel', { deltaY, bubbles: true }));
  intro.scrollTop = 0;
  await wait(220);
  wheel(80);
  intro.scrollTop = intro.scrollHeight;
  const introBottom = intro.scrollTop;
  intro.scrollBy(0, 2000);
  await wait(100);
  wheel(80);
  assert(stage.dataset.homeView === 'intro' && cities.inert, 'Momentum from reaching the bottom must not enter Cities');
  assert(intro.scrollTop === introBottom, 'Intro must stop at its own bottom');
  const preview = intro.querySelector('[data-cities-preview]');
  assert(preview.getBoundingClientRect().height >= 24 && preview.getBoundingClientRect().height <= 32, 'Cities preview must remain a slim strip');
  assert(getComputedStyle(preview).backgroundColor === getComputedStyle(cities).backgroundColor, 'Preview must match Cities');
  assert(getComputedStyle(intro).backgroundColor === getComputedStyle(cities).backgroundColor, 'Rounded corners must reveal the Cities color');
  assert(parseFloat(getComputedStyle(intro.querySelector('[data-home-card]')).borderBottomLeftRadius) >= 48, 'Home card must have rounded bottom corners');
  assert(cities.getBoundingClientRect().top >= innerHeight - 1, 'City content must stay outside the intro viewport');
  const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  await wait(220);
  wheel(80);
  // Allow the short wheel wind-up before sampling the slide itself.
  await wait(reduced ? 200 : 500);
  const midSlide = cities.getBoundingClientRect().top;
  assert(midSlide > 0 && midSlide < innerHeight, 'Entrance must visibly slide rather than jump, including reduced motion');
  if (!reduced) assert(document.querySelector('[data-transition-effect="sand"]'), 'Cities entrance must show the sandstorm');
  else assert(!document.querySelector('[data-transition-effect]'), 'Reduced motion must skip the weather effects');
  await wait(1200);
  assert(stage.dataset.homeView === 'cities' && stage.dataset.transitioning === 'false', 'Entrance must finish');
  assert(Math.abs(cities.getBoundingClientRect().top) <= 1, 'Cities must settle without shaking');
  assert(!document.querySelector('[data-transition-effect]'), 'Sandstorm must clear after arrival');
  assert(intro.inert && !cities.inert, 'Only the active view may receive input');
  assert(document.activeElement === back, 'Focus must move to the return arrow');
  const backBounds = back.getBoundingClientRect();
  const cityBounds = cities.getBoundingClientRect();
  assert(Math.abs(backBounds.left + backBounds.width / 2 - (cityBounds.left + cities.clientWidth / 2)) < 2, 'Back arrow must be centered');
  cities.scrollTop = cities.scrollHeight;
  await wait(100);
  assert(cities.scrollTop > 0, 'All four cities must be scrollable');
  assert(back.getBoundingClientRect().top >= 0 && back.getBoundingClientRect().bottom < innerHeight, 'Back arrow must remain visible');
  wheel(-80, cities);
  cities.scrollTo({ top: 0, behavior: 'instant' });
  cities.scrollBy(0, -2000);
  await wait(100);
  wheel(-80, cities);
  assert(stage.dataset.homeView === 'cities' && intro.inert, 'Momentum from reaching the top must stay in Cities');
  await wait(220);
  wheel(-80, cities);
  await wait(500);
  if (!reduced) assert(document.querySelector('[data-transition-effect="water"]'), 'Return must show the golden-water wash');
  await wait(1200);
  assert(stage.dataset.homeView === 'intro' && stage.dataset.transitioning === 'false', 'Upward scrolling must finish returning');
  assert(Math.abs(intro.scrollTop - introBottom) <= 1, 'Return must preserve the intro position');
  assert(document.activeElement === enter, 'Return must restore focus to the entry arrow');
  assert(cities.inert && !intro.inert, 'Return must restore the scroll gate');
  assert(!document.querySelector('[data-transition-effect]'), 'Water must clear after returning');
  enter.click();
  await wait(1700);
  assert(stage.dataset.homeView === 'cities', 'The entry button must still work');
  back.click();
  await wait(1700);
  const touch = (type, y, target = intro) => {
    const event = new Event(type, { bubbles: true });
    Object.defineProperty(event, 'touches', { value: [{ clientX: 100, clientY: y }] });
    target.dispatchEvent(event);
  };
  touch('touchstart', 400);
  touch('touchmove', 320);
  await wait(1700);
  assert(stage.dataset.homeView === 'cities', 'A fresh upward swipe at the bottom must enter Cities');
  touch('touchstart', 320, cities);
  touch('touchmove', 400, cities);
  await wait(1700);
  assert(stage.dataset.homeView === 'intro', 'A fresh downward swipe at the top must return home');
  assert(intro.scrollWidth <= intro.clientWidth && cities.scrollWidth <= cities.clientWidth, 'Views must not overflow horizontally');
  assert(scrollY === 0, 'Document scrolling must not compete with view transitions');
  return { status: 'PASS', viewport: `${innerWidth}x${innerHeight}`, reducedMotion: reduced, midSlide: Math.round(midSlide), introBottom };
})();
